SC-0 feat: branch name rule 1.0.46

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -32,6 +32,23 @@ pipelines:
               fi
 
       - step:
+          name: Check and Run Tests
+          script:
+            - echo "Checking for test files..."
+            - |
+              if find ./projects -name "*.spec.ts" | grep -q .; then
+                echo "Running tests..."
+                npx ng test --watch=false
+
+                if [ $? -ne 0 ]; then
+                  echo "Tests failed."
+                  exit 1
+                fi
+              else
+                echo "No test files found. Skipping tests..."
+              fi
+
+      - step:
           name: Clean Up Merged Feature Branches
           script:
             - echo "Fetching all branches..."
@@ -87,6 +104,23 @@ pipelines:
               if [[ ! "$BITBUCKET_BRANCH" =~ ^feature- ]]; then
                 echo "Branch name must start with 'feature-'.";
                 exit 1;
+              fi
+
+      - step:
+          name: Check and Run Tests
+          script:
+            - echo "Checking for test files..."
+            - |
+              if find ./projects -name "*.spec.ts" | grep -q .; then
+                echo "Running tests..."
+                npx ng test --watch=false
+
+                if [ $? -ne 0 ]; then
+                  echo "Tests failed."
+                  exit 1
+                fi
+              else
+                echo "No test files found. Skipping tests..."
               fi
 
       - step:
