SC-0 feat: branch name rule 1.0.33

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -14,13 +14,13 @@ pipelines:
           - echo "Validating branch name..."
           - current_branch=$(git rev-parse --abbrev-ref HEAD)
           - target_branch=${BITBUCKET_PR_DESTINATION_BRANCH:-$current_branch}
-          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" && ("$target_branch" == "main" || "$target_branch" == "develop") ];
-          - then
+          - if [ -n "$BITBUCKET_PR_DESTINATION_BRANCH" ] && { [ "$target_branch" == "main" ] || [ "$target_branch" == "develop" ]; }; then
             echo "Not validating branch name because it's a PR to 'main' or 'develop'.";
             else
-            if [ !"$current_branch" =~ ^feature-.* ]; then
+            if [[ ! "$current_branch" =~ ^feature-.* ]]; then
             echo "Branch name must start with 'feature-'.";
             exit 1;
+            fi
             fi
 
     - step:
@@ -30,15 +30,15 @@ pipelines:
           - git fetch --all
           - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == "develop" ]; then
             echo "PR is targeting 'develop'. Proceeding with branch cleanup...";
-            merged_branches=$(git branch -r --merged origin/develop | grep -v '\->' | grep -E 'origin/feature-.*');
+            merged_branches=$(git branch -r --merged origin/develop | grep -v '\->' | grep -E 'origin/feature-.*')
             echo "$merged_branches" | while read -r branch; do
-            if [ "$branch" =~ ^origin/feature-.* ]; then
-            echo "Deleting merged branch ${branch#origin/}";
-            git push origin --delete "${branch#origin/}";
+            if [[ "$branch" =~ ^origin/feature-.* ]]; then
+            echo "Deleting merged branch ${branch#origin/}"
+            git push origin --delete "${branch#origin/}"
             fi
-            done;
+            done
             else
-            echo "Not a merge to 'develop', skipping branch cleanup.";
+            echo "Not a merge to 'develop', skipping branch cleanup."
             fi
 
     - step:
@@ -46,20 +46,20 @@ pipelines:
         script:
           - echo "Checking PR source branch..."
           - if [ -n "$BITBUCKET_PR_DESTINATION_BRANCH" ]; then
-            echo "PR destination is set to $BITBUCKET_PR_DESTINATION_BRANCH";
+            echo "PR destination is set to $BITBUCKET_PR_DESTINATION_BRANCH"
             if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == "main" ]; then
-            echo "PR targets 'main'. Verifying source branch...";
+            echo "PR targets 'main'. Verifying source branch..."
             if [ "$BITBUCKET_BRANCH" != "develop" ]; then
-            echo "Error PR to 'main' must come from 'develop'. Current source branch is $BITBUCKET_BRANCH.";
-            exit 1;
+            echo "Error PR to 'main' must come from 'develop'. Current source branch is $BITBUCKET_BRANCH."
+            exit 1
             else
-            echo "PR source branch is 'develop'. Check passed.";
+            echo "PR source branch is 'develop'. Check passed."
             fi
             else
-            echo "PR does not target 'main', skipping source branch check.";
+            echo "PR does not target 'main', skipping source branch check."
             fi
             else
-            echo "Not in a PR context, skipping source branch check.";
+            echo "Not in a PR context, skipping source branch check."
             fi
 
     - step:
