SC-0 feat: branch name rule 1.0.3

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -17,13 +17,15 @@ pipelines:
         script:
           - echo "Checking if the pull request is from 'develop' branch..."
           - |
-            git fetch --all
-            base_branch=$(git rev-parse --abbrev-ref HEAD)
-            if [ "$base_branch" == "main" ]; then
-            source_branch=$(git rev-parse --abbrev-ref $(git merge-base HEAD $(git for-each-ref --format '%(upstream:short)' $(git symbolic-ref -q HEAD))))
-            if [ "$source_branch" != "develop" ]; then
-              echo "Error: Pull request to 'main' must come from 'develop' branch.";
-              exit 1;
+            if [ "$BITBUCKET_PR_DESTINATION" == "main" ]; then
+              git fetch --all
+              source_branch=$BITBUCKET_PR_SOURCE
+              if [ "$source_branch" != "develop" ]; then
+                echo "Error: Pull request to 'main' must come from 'develop' branch.";
+                exit 1;
+              fi
+            else
+              echo "Not a pull request to 'main', skipping branch check.";
             fi
 
     - step:
